### ISSUE TITLE
addPost rubino

### ISSUE THREAD

**Issue by MasterKali06** [Bahman-Ahmadi/rubika#14]
salam vakht bekheir
mikhastam bebinam shoma addPost moafagh dashtid?
chon man payloadam hame mavaredesh okeye vali bazam INVALID_INPUT migiram
engar ke mavaredi ke tooye code hast ya nakhesi dare ya ye jaye karesh milange
payloadi ke mifrestam ine
{
  "api_version": "0",
  "auth": auth,
  "client": {
    "app_name": "Main",
    "app_version": "2.9.8",
    "platform": "Android",
    "package": "app.rbmain.a",
    "lang_code": "fa"
  },
  "data": {
    "caption": "First post - test",
    "file_id": "6450dc683b775004a3c6e570",
    "hash_file_receive": "e46be95a-daf7-479b-9312-fd4c017995bb",
    "height": "200",
    "width": "200",
    "post_type": "Picture",
    "is_multi_file": false,
    "rnd": 874244105,
    "thumbnail_file_id": "6450dc683b775004c943ce2b",
    "thumbnail_hash_file_receive": "c836679c-5133-46a3-97c8-96ef714bdfb5",
    "profile_id": profile_id
  },
  "method": "addPost"
}

vali kolan invalid input migiram
agar javab bedid kheili mamnoon misham

**Comment by mahdigudarzi** [comment]
من یه کد برای این نوشتم که کار میکنه البته برای این کتابخونه نیست میخوایید شیر کنم؟
